default:
  image: python:3.9.20@sha256:f6688258e79f67a535ef2301b1a3475e37e0b77705e7e7e0146c6557c3b61763
  tags:
    - pangea-internal

stages:
  - lint
  - build
  - unit_tests
  - integration_tests
  - examples
  - publish

.setup:
  update-pip:
    - pip install --upgrade pip
    - pip --version

  update-poetry:
    - pip install --upgrade poetry
    - poetry --version

include:
  - /examples/.examples-ci.yml
  - /packages/pangea-django/.django-ci.yml
  - /packages/pangea-sdk/.sdk-ci.yml
