default:
  image: python:3.9.20@sha256:2992dbc3626ab64f34207d4125203a8977047e0b214e9588349b45f5c1bea61a
  tags:
    - pangea-internal

stages:
  - lint
  - build
  - unit_tests
  - integration_tests
  - examples
  - publish

.setup:
  update-pip:
    - pip install --upgrade pip
    - pip --version

  update-poetry:
    - pip install --upgrade poetry
    - poetry --version

include:
  - /examples/.examples-ci.yml
  - /packages/pangea-django/.django-ci.yml
  - /packages/pangea-sdk/.sdk-ci.yml
