.pangea-sdk-base:
  before_script:
    - cd packages/pangea-sdk/
    - pip install poetry
    - poetry install
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

.pangea-sdk-publish:
  before_script:
    - cd packages/pangea-sdk/
    - pip install poetry
    - poetry install
  rules:
    - if: $CI_COMMIT_BRANCH == "release"
      changes:
        - packages/pangea-sdk/**/*
      when: on_success

py_lint:
  extends: .pangea-sdk-base
  stage: lint
  script:
    - poetry run black .

testing:
  extends: .pangea-sdk-base
  stage: unit_tests
  script:
    - poetry run python -m unittest tests

integration:
  extends: .pangea-sdk-base
  stage: integration_tests
  script:
    - poetry run python -m unittest tests.integration

building:
  extends: .pangea-sdk-publish
  stage: build
  script:
    - poetry build
    - poetry publish --username __token__ --password $PYPI_SDK_TOKEN
    - poetry config repositories.artifactory "https://builder.scranton.dev.pangea.cloud/artifactory/api/pypi/pypi"
    - poetry publish --repository artifactory -u poetry -p "${ARTIFACTORY_PUBLISH_TOKEN}"
