.pangea-django-base:
  before_script:
    - cd packages/pangea-django/
    - pip install poetry
    - poetry install
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

django_lint:
  extends: .pangea-django-base
  stage: lint
  script:
    - poetry run black --check .

pangea-django-publish:
  stage: publish
  extends: .pangea-django-base
  script:
    - poetry build
    - poetry publish --username __token__ --password $PYPI_SDK_TOKEN
  rules:
    - if: $CI_COMMIT_BRANCH == "release"
      changes:
        - packages/pangea-django/**/*
      when: on_success
