.django-base:
  image: python:3.9@sha256:a847112640804ed2d03bb774d46bb1619bd37862fb2b7e48eebe425a168c153b
  before_script:
    - !reference [.setup, update-pip]
    - !reference [.setup, update-poetry]

    - cd packages/pangea-django/
    - poetry check --lock
    - poetry install
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

django-build:
  extends: .django-base
  stage: build
  script:
    - poetry build
  artifacts:
    paths: ["packages/pangea-django/dist"]
    when: on_success

django-publish:
  extends: .django-base
  stage: publish
  needs: [django-build]
  script:
    - bash ../../dev/validate_tag.sh $CI_COMMIT_TAG
    - poetry publish --username __token__ --password $PYPI_SDK_TOKEN
  rules:
    - if: $CI_COMMIT_TAG =~ /pangea-django\/.+/
