.django-base:
  image: python:3.8
  before_script:
    - !reference [.setup, update-pip]
    - !reference [.setup, update-poetry]

    - cd packages/pangea-django/
    - poetry check --lock
    - poetry install
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

django-lint-black:
  extends: .django-base
  stage: lint
  needs: []
  script:
    - poetry run black .

django-build:
  extends: .django-base
  stage: build
  script:
    - poetry build
  artifacts:
    paths: ["packages/pangea-django/dist"]
    when: on_success

django-publish:
  extends: .django-base
  stage: publish
  needs: [django-build]
  script:
    - bash ../../dev/validate_tag.sh
    - poetry publish --username __token__ --password $PYPI_SDK_TOKEN
  rules:
    - if: $CI_COMMIT_TAG =~ /pangea-django\/.+/
