.django-base:
  before_script:
    - cd packages/pangea-django/
    - uv sync --all-extras --all-packages --dev
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

django-build:
  extends: .django-base
  stage: build
  needs: []
  script:
    - uv build -o dist
  artifacts:
    paths: ["packages/pangea-django/dist"]
    when: on_success

django-publish:
  extends: .django-base
  stage: publish
  needs: [django-build]
  script:
    - bash ../../dev/validate_tag.sh $CI_COMMIT_TAG
    - uv publish --username __token__ --password $PYPI_SDK_TOKEN
  rules:
    - if: $CI_COMMIT_TAG =~ /pangea-django\/.+/
